config/routes.rb
Rails.application.routes.draw do
  
root 'recipes#index'
get 'pages/about'
  devise_for :users
  resources :recipes
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light"> 
    <%= link_to "Recipe App", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="container">
      <ul class="nav nav-pills">
        <li class="nav-item nav-link"><%= link_to "About", pages_about_path %></li>
        <% if user_signed_in? %>
      <ul class="nav nav-pills nav-fill">
         <li class="nav-item nav-link"><%= link_to 'Submit Recipe', new_recipe_path %></li>
         <li class="nav-item nav-link"><%= link_to 'Account', edit_user_registration_path %></li>
         <li class="nav-item nav-link"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
      </ul>
     <% else %>
      <ul class="nav nav-pills nav-fill">
         <li class="nav-item nav-link"><%= link_to 'Sign up', new_user_registration_path%></li>
         <li class="nav-item nav-link"><%= link_to 'Sign in', new_user_session_path %></li><% end %>
      </ul>
     
      </ul>
    </div>
    </div>
  </nav>
    <div id="main_content" class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
     <% end %>
    <div id="content" class="col-md-9 center-block">
      <%= yield %>
    </div>
  </div>
</body>
</html>